{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-external-service
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .name }}
spec:
  type: ExternalName
  externalName: {{ .external_name }}
  ports:
  {{- range .service_ports }}
    - port: {{ .port }}
      targetPort: {{ .target_port }}
      name: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
{{- end }}
