{{- range .Values.services }}
{{- $serviceName := .name }}
{{- range .ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}-{{ .host | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .ingressClassName }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ $serviceName }}-external-service
                port:
                  number: {{ .port }}
{{- end }}
{{- end }}
