{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-external-service
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .name }}
spec:
  ports:
  {{- range .service_ports }}
    - port: {{ .port }}
      targetPort: {{ .target_port }}
      name: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name }}-external-service-endpoint-slice
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .name }}
    kubernetes.io/service-name: {{ .name }}-external-service
    endpointslice.kubernetes.io/managed-by: external-service-ingresses
addressType: IPv4
ports:
{{- range .service_ports }}
  - name: {{ .name }}
    protocol: {{ .protocol | default "TCP" }}
    port: {{ .target_port }}
{{- end }}
endpoints:
  - addresses:
    - {{ .external_ip }}
{{- end }}
