{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-external-service
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .name }}
spec:
  type: ClusterIP
  ports:
  {{- range .service_ports }}
    - port: {{ .port }}
      targetPort: {{ .target_port }}
      name: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}-external-service
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .name }}
subsets:
  - addresses:
    - ip: {{ .external_ip }}
    ports:
    {{- range .service_ports }}
      - port: {{ .target_port }}
        name: {{ .name }}
        protocol: {{ .protocol | default "TCP" }}
    {{- end }}
{{- end }}
